# 1️⃣ Используем Node.js для сборки фронтенда
FROM node:18 AS build

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# 2️⃣ Используем Nginx для раздачи фронта
FROM nginx:latest

# Копируем Nginx конфиг
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Копируем собранный фронт в папку, откуда Nginx будет раздавать файлы
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
